// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: revoke_token.sql

package database

import (
	"context"
)

const updateToken = `-- name: UpdateToken :exec
UPDATE refresh_tokens
SET updated_at = NOW(), revoked_at = NOW()
WHERE token = $1
`

func (q *Queries) UpdateToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, updateToken, token)
	return err
}
