// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: set_chirpy_red.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const setChirpyRed = `-- name: SetChirpyRed :exec
UPDATE users
SET updated_at = NOW(), is_chirpy_red = TRUE
WHERE id = $1
`

func (q *Queries) SetChirpyRed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, setChirpyRed, id)
	return err
}
